# Generated by Django 6.0.5 on 2026-05-20 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['user__first_name'], 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nome'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='consulta',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='medico',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='medico',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
